Week 1 Basic Changes
rqtrinh/software-product-sprint pull request #2
Opened 2022-06-02 19:20 UTC by rqtrinh

Add image, bio, CSS styling, and random greeting. Week 1 tutorial up to step 11/14.

2022-06-06 14:52 UTC, RyanSCollins requested changes

2022-06-06 14:52 UTC, RyanSCollins commented on portfolio/src/main/webapp/index.html
> +      <img src ="/images/selfie.jpg" width="300" height="300" class="center"/>
Nit: Add alt text describing the image for accessibility.
https://google.github.io/styleguide/htmlcssguide.html#Multimedia_Fallback

2022-06-06 14:52 UTC, RyanSCollins commented on portfolio/src/main/webapp/index.html
> +      <img src ="/images/selfie.jpg" width="300" height="300" class="center"/>
Try to keep presentational concerns like width/height and centering in the stylesheet and have the html file contain only content.
https://google.github.io/styleguide/htmlcssguide.html#Separation_of_Concerns

2022-06-07 04:58 UTC, rqtrinh commented on portfolio/src/main/webapp/index.html
> +      <img src ="/images/selfie.jpg" width="300" height="300" class="center"/>
In the commit to resolve this issue, I added an id "selfie" to describe the image for accessibility.

2022-06-07 04:59 UTC, rqtrinh commented on portfolio/src/main/webapp/index.html
> +      <img src ="/images/selfie.jpg" width="300" height="300" class="center"/>
In the new commit, I add an id "selfie". I used this id to style width/height in the CSS stylesheet.

2022-06-07 15:06 UTC, RyanSCollins approved these changes

2022-06-07 22:21 UTC, merged