Week 1 Paragraphs about Me
rqtrinh/software-product-sprint pull request #3
Opened 2022-06-03 04:36 UTC by rqtrinh

Add paragraphs of biography, experience, and me! Add headers for organization.

2022-06-06 18:23 UTC, RyanSCollins requested changes

2022-06-06 18:23 UTC, RyanSCollins commented on portfolio/src/main/webapp/index.html
> +      <p>I have had many experiences in my career. My first experience is
Nitpick: tense, "is"->"was"

2022-06-06 18:23 UTC, RyanSCollins commented on portfolio/src/main/webapp/index.html
> +          intering at Avanade as a Full Stack Developer.
Nit: spelling/typo, "interning"

2022-06-07 05:04 UTC, rqtrinh commented on portfolio/src/main/webapp/index.html
> +      <p>I have had many experiences in my career. My first experience is
Fixed grammar mistake

2022-06-07 05:04 UTC, rqtrinh commented on portfolio/src/main/webapp/index.html
> +          intering at Avanade as a Full Stack Developer.
Fixed spelling mistake

2022-06-07 15:06 UTC, RyanSCollins approved these changes

2022-06-07 22:28 UTC, merged