Storing form information in database
rqtrinh/software-product-sprint pull request #9
Opened 2022-06-17 05:37 UTC by rqtrinh

Using datastore, to store the contact information from the form on my page

2022-06-23 15:46 UTC, RyanSCollins requested changes

2022-06-23 15:46 UTC, RyanSCollins commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +import com.google.cloud.datastore.Query;
Keep sorted

2022-06-23 15:46 UTC, RyanSCollins commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +    KeyFactory keyFactory = datastore.newKeyFactory().setKind("Contact");
Consider defining constants for strings that are used across multiple datastore interactions.

2022-06-26 18:38 UTC, rqtrinh commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +import com.google.cloud.datastore.Query;
Resorted in the latest push

2022-06-28 14:17 UTC, RyanSCollins approved these changes

2022-06-30 03:48 UTC, merged